FROM golang:1.23 AS building

COPY . /building
WORKDIR /building

RUN make sidecar

FROM alpine:3.16.3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/sidecar /usr/bin/sidecar

ENTRYPOINT ["/usr/bin/sidecar"]
