FROM golang:1.23 AS building

COPY . /building
WORKDIR /building

RUN make router

FROM alpine:3.16.3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/router /usr/bin/router

ENTRYPOINT ["/usr/bin/router"]
