services:
    - cluster: cluster-a.local
      name: backend
      namespace: default
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetport: 8080
        - name: http2
          port: 88
          protocol: TCP
          targetport: 8888
