apiVersion: v1
kind: Pod
metadata:
  name: k3s-server
spec:
  containers:
    - name: k3s
      image: rancher/k3s:v1.28.15-k3s1
      ports:
        - containerPort: 7443
          hostPort: 7443
          protocol: TCP
      volumeMounts:
        - name: data
          mountPath: /var/lib/rancher/k3s
        - name: etc
          mountPath: /etc/rancher/k3s
      args:
        - server
        - --disable-agent
        - --disable-controller-manager
        - --disable-scheduler
        - --disable=scheduler,coredns,servicelb,traefik,local-storage,metrics-server
        - --https-listen-port=7443
        - --tls-san=172.31.19.105
        - --tls-san='*.edgewize.io'
    - name: frps
      image: tkeelio/kube-frps:latest
      ports:
        - containerPort: 7000
          hostPort: 7000
          protocol: TCP
      command: ["frps"]
      args:
        - -c
        - /etc/frp/frps.ini
  restartPolicy: Never
  volumes:
    - name: data
      hostPath:
        path: /var/lib/rancher/k3s
    - name: etc
      hostPath:
        path: /etc/rancher/k3s