apiVersion: v1
kind: Pod
metadata:
  name: dns-hijack-test-1
spec:
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 127.0.0.2
    searches:
      - default.svc.cluster.local
  containers:
    - name: sidecar
      image: tkeelio/service-keel-sidecar:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: SIDECAR_MAPPED_SERVICES
          value: "mysql"
        - name: SIDECAR_IP_RANGE
          value: "127.0.66.0/24"
        - name: SIDECAR_DNS_ADDR
          value: "127.0.0.2:53"
    - name: tester
      image: busybox:1.35
      command: ["sh", "-c", "sleep 3600"]
  restartPolicy: Never 