apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: default
  annotations:
    servicekeel.io/imported-services: |
      services:
        - cluster: cluster-a.local
          name: simple-server
          namespace: default
          ports:
            - name: tcp
              port: 8080
              protocol: TCP
              targetport: 8080
            - name: ntp
              port: 123
              protocol: UDP
              targetport: 123
        - cluster: cluster-a.local
          name: simple-server2
          namespace: default
          ports:
            - name: tcp
              port: 8080
              protocol: TCP
              targetport: 8080
            - name: ntp
              port: 123
              protocol: UDP
              targetport: 123
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - "127.0.0.2"
    searches:
      - "default.svc.cluster-a.local"
      - "svc.cluster-a.local"
      - "cluster-a.local"
    options:
      - name: ndots
        value: "5"
  containers:
    - name: client
      image: alpine:latest
      command:
        - sh
        - -c
        - |
          while true; do
            echo "========================="
            echo "Testing simple-server..."
            echo "TCP Test:"
            wget -q -O- http://simple-server.default:8080/
            echo -e "\nHealth Check:"
            wget -q -O- http://simple-server.default:8080/health
            
            echo -e "\nUDP Test:"
            echo "Testing UDP port 123..."
            echo "test" | nc -u -w 1 simple-server.default 123
            echo "UDP test completed"
            
            echo -e "\n========================="
            echo "Testing simple-server2..."
            echo "TCP Test:"
            wget -q -O- http://simple-server2.default:8080/
            echo -e "\nHealth Check:"
            wget -q -O- http://simple-server2.default:8080/health
            
            echo -e "\nUDP Test:"
            echo "Testing UDP port 123..."
            echo "test" | nc -u -w 1 simple-server2.default 123
            echo "UDP test completed"
            
            echo -e "\n=========================\n"
            sleep 5
          done
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: UDP
    - name: sidecar
      image: tkeelio/service-keel-sidecar:latest
      env:
        - name: SIDECAR_IP_RANGE
          value: "127.0.66.0/24"
        - name: SIDECAR_DNS_ADDR
          value: "127.0.0.2:53"
        - name: SIDECAR_FRP_SERVER_LISTEN
          value: "/tmp/frp.sock"
      volumeMounts:
        - name: podinfo
          mountPath: /etc/servicekeel
        - name: frps-socket
          mountPath: /tmp/frp.sock
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "exported-services-config.yaml"  # 第一个注解的文件名
            fieldRef:
              fieldPath: metadata.annotations['servicekeel.io/exported-services']
          - path: "imported-services-config.yaml"  # 第二个注解的文件名
            fieldRef:
              fieldPath: metadata.annotations['servicekeel.io/imported-services']
    - name: frps-socket
      hostPath:
        path: /tmp/frp.sock
        type: Socket 